// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnwyiMc9iiljldLKFXbA1XlZz4vCy7QcY',
    appId: '1:2862981366:web:62b7a5fef0f8516d03ccd7',
    messagingSenderId: '2862981366',
    projectId: 'smarthealth-e8b39',
    authDomain: 'smarthealth-e8b39.firebaseapp.com',
    storageBucket: 'smarthealth-e8b39.appspot.com',
    measurementId: 'G-D2F01JYFQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKQDH89yze0zMJSjJME6S5j73oxTp7hGI',
    appId: '1:2862981366:android:eb5bf1310aecf86603ccd7',
    messagingSenderId: '2862981366',
    projectId: 'smarthealth-e8b39',
    storageBucket: 'smarthealth-e8b39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAaNZ_TE7V9_yeqxO69Upeu19Hg2uG6T4',
    appId: '1:2862981366:ios:cf2f21b6630f837c03ccd7',
    messagingSenderId: '2862981366',
    projectId: 'smarthealth-e8b39',
    storageBucket: 'smarthealth-e8b39.appspot.com',
    iosClientId: '2862981366-6ast8qrlnoku765erbnp6il15vns86el.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarthealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAaNZ_TE7V9_yeqxO69Upeu19Hg2uG6T4',
    appId: '1:2862981366:ios:cf2f21b6630f837c03ccd7',
    messagingSenderId: '2862981366',
    projectId: 'smarthealth-e8b39',
    storageBucket: 'smarthealth-e8b39.appspot.com',
    iosClientId: '2862981366-6ast8qrlnoku765erbnp6il15vns86el.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarthealth',
  );
}
